print("Welcome to Mad Libs! Enter the following information: ")
name_of_person_1 = input("Tell me a name.\n")
name_of_place  = input("Tell me a place.\n")
time = input("Tell me a time.\n")
color = ("Tell me a color.\n")
verb = input("Tell me a verb.\n")
name_of_person_2 = input("Tell me another name.\n")
place2 = input("Tell me a place inside the place you told me earlier. For example, if you said 'park', then you could now say 'playground'.")
print(name_of_person_1 + "went to " + name_of_place + " at " + time + " with " + name_of_person_2 + " and " + verb + " on/in " + place2) 
