a=input("What is first term of the addition problem? For example, it could be 3.\n")
b=input("What is the second term of the addition problem? For example, it could be 9.\n")
print ("The sum of these two numbers is...")
sum = float(a) + float(b)
print (sum)
