a=input("What is the first term of your multiplication problem? \n")
b=input("What is the second term of your multiplication problem? \n")
print ("The product of these two numbers is...")
product = float(a) * float(b)
print (product)
